package com.google.android.gms.internal;

import android.content.Context;
import android.support.v4.view.accessibility.AccessibilityEventCompat;
import android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
import com.google.android.gms.ads.internal.zzw;
import com.google.firebase.remoteconfig.FirebaseRemoteConfig;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
import p000a.p001a.p002a.p003a.p004a.p006b.AbstractSpiCall;

@zzme
public final class zzgd {
    public static final zzfz<Long> zzBA;
    public static final zzfz<Long> zzBB;
    public static final zzfz<Integer> zzBC;
    public static final zzfz<Boolean> zzBD;
    public static final zzfz<String> zzBE;
    public static final zzfz<Long> zzBF;
    public static final zzfz<Boolean> zzBG;
    public static final zzfz<Long> zzBH;
    public static final zzfz<Boolean> zzBI;
    public static final zzfz<Integer> zzBJ;
    public static final zzfz<Long> zzBK;
    public static final zzfz<Boolean> zzBL;
    public static final zzfz<Boolean> zzBM;
    public static final zzfz<String> zzBN;
    public static final zzfz<Boolean> zzBO;
    public static final zzfz<Boolean> zzBP;
    public static final zzfz<Float> zzBQ;
    public static final zzfz<String> zzBR;
    public static final zzfz<String> zzBS;
    public static final zzfz<Boolean> zzBT;
    public static final zzfz<Boolean> zzBU;
    public static final zzfz<Boolean> zzBV;
    public static final zzfz<String> zzBW;
    public static final zzfz<String> zzBX;
    public static final zzfz<String> zzBY;
    public static final zzfz<Boolean> zzBZ;
    public static final zzfz<String> zzBg;
    public static final zzfz<String> zzBh;
    public static final zzfz<Boolean> zzBi;
    public static final zzfz<String> zzBj;
    public static final zzfz<Boolean> zzBk;
    public static final zzfz<String> zzBl;
    public static final zzfz<Boolean> zzBm;
    public static final zzfz<Boolean> zzBn;
    public static final zzfz<String> zzBo;
    public static final zzfz<Boolean> zzBp;
    public static final zzfz<String> zzBq;
    public static final zzfz<String> zzBr;
    public static final zzfz<Boolean> zzBs;
    public static final zzfz<Integer> zzBt;
    public static final zzfz<String> zzBu;
    public static final zzfz<String> zzBv;
    public static final zzfz<Integer> zzBw;
    public static final zzfz<Integer> zzBx;
    public static final zzfz<Integer> zzBy;
    public static final zzfz<Integer> zzBz;
    public static final zzfz<Boolean> zzCA;
    public static final zzfz<Boolean> zzCB;
    public static final zzfz<Boolean> zzCC;
    public static final zzfz<Boolean> zzCD;
    public static final zzfz<String> zzCE;
    public static final zzfz<String> zzCF;
    public static final zzfz<Boolean> zzCG;
    public static final zzfz<Integer> zzCH;
    public static final zzfz<Boolean> zzCI;
    public static final zzfz<String> zzCJ;
    public static final zzfz<Boolean> zzCK;
    public static final zzfz<String> zzCL;
    public static final zzfz<String> zzCM;
    public static final zzfz<Boolean> zzCN;
    public static final zzfz<Long> zzCO;
    public static final zzfz<Boolean> zzCP;
    public static final zzfz<Long> zzCQ;
    public static final zzfz<Long> zzCR;
    public static final zzfz<Boolean> zzCS;
    public static final zzfz<Long> zzCT;
    public static final zzfz<Boolean> zzCU;
    public static final zzfz<Boolean> zzCV;
    public static final zzfz<String> zzCW;
    public static final zzfz<Boolean> zzCX;
    public static final zzfz<Long> zzCY;
    public static final zzfz<String> zzCZ;
    public static final zzfz<String> zzCa;
    public static final zzfz<Boolean> zzCb;
    public static final zzfz<Boolean> zzCc;
    public static final zzfz<Integer> zzCd;
    public static final zzfz<Integer> zzCe;
    public static final zzfz<Integer> zzCf;
    public static final zzfz<Integer> zzCg;
    public static final zzfz<Integer> zzCh;
    public static final zzfz<Boolean> zzCi;
    public static final zzfz<Integer> zzCj;
    public static final zzfz<Boolean> zzCk;
    public static final zzfz<Integer> zzCl;
    public static final zzfz<Integer> zzCm;
    public static final zzfz<String> zzCn;
    public static final zzfz<String> zzCo;
    public static final zzfz<Boolean> zzCp;
    public static final zzfz<Boolean> zzCq;
    public static final zzfz<Long> zzCr;
    public static final zzfz<String> zzCs;
    public static final zzfz<String> zzCt;
    public static final zzfz<Boolean> zzCu;
    public static final zzfz<Boolean> zzCv;
    public static final zzfz<Boolean> zzCw;
    public static final zzfz<String> zzCx;
    public static final zzfz<Boolean> zzCy;
    public static final zzfz<Boolean> zzCz;
    public static final zzfz<Boolean> zzDA;
    public static final zzfz<Boolean> zzDB;
    public static final zzfz<Boolean> zzDC;
    public static final zzfz<Boolean> zzDD;
    public static final zzfz<Boolean> zzDE;
    public static final zzfz<String> zzDF;
    public static final zzfz<Long> zzDG;
    public static final zzfz<Long> zzDH;
    public static final zzfz<Boolean> zzDI;
    public static final zzfz<Boolean> zzDJ;
    public static final zzfz<Boolean> zzDK;
    public static final zzfz<Long> zzDL;
    public static final zzfz<Long> zzDM;
    public static final zzfz<Boolean> zzDN;
    public static final zzfz<Long> zzDO;
    public static final zzfz<Boolean> zzDP;
    public static final zzfz<Boolean> zzDQ;
    public static final zzfz<Boolean> zzDR;
    public static final zzfz<Boolean> zzDS;
    public static final zzfz<Boolean> zzDT;
    public static final zzfz<Boolean> zzDU;
    public static final zzfz<Boolean> zzDV;
    public static final zzfz<Boolean> zzDW;
    public static final zzfz<Boolean> zzDX;
    public static final zzfz<Boolean> zzDY;
    public static final zzfz<Boolean> zzDZ;
    public static final zzfz<Integer> zzDa;
    public static final zzfz<Integer> zzDb;
    public static final zzfz<Boolean> zzDc;
    public static final zzfz<Boolean> zzDd;
    public static final zzfz<String> zzDe;
    public static final zzfz<String> zzDf;
    public static final zzfz<Integer> zzDg;
    public static final zzfz<Integer> zzDh;
    public static final zzfz<Integer> zzDi;
    public static final zzfz<String> zzDj;
    public static final zzfz<Integer> zzDk;
    public static final zzfz<Integer> zzDl;
    public static final zzfz<Float> zzDm;
    public static final zzfz<Integer> zzDn;
    public static final zzfz<String> zzDo;
    public static final zzfz<String> zzDp;
    public static final zzfz<String> zzDq;
    public static final zzfz<Boolean> zzDr;
    public static final zzfz<Boolean> zzDs;
    public static final zzfz<String> zzDt;
    public static final zzfz<Long> zzDu;
    public static final zzfz<Boolean> zzDv;
    public static final zzfz<Long> zzDw;
    public static final zzfz<Boolean> zzDx;
    public static final zzfz<Boolean> zzDy;
    public static final zzfz<Boolean> zzDz;
    public static final zzfz<Long> zzEA;
    public static final zzfz<Integer> zzEB;
    public static final zzfz<Integer> zzEC;
    public static final zzfz<Boolean> zzED;
    public static final zzfz<String> zzEE;
    public static final zzfz<Long> zzEF;
    public static final zzfz<String> zzEG;
    public static final zzfz<Long> zzEH;
    public static final zzfz<String> zzEI;
    public static final zzfz<Boolean> zzEJ;
    public static final zzfz<String> zzEK;
    public static final zzfz<Long> zzEL;
    public static final zzfz<String> zzEM;
    public static final zzfz<String> zzEN;
    public static final zzfz<String> zzEO;
    public static final zzfz<String> zzEP;
    public static final zzfz<String> zzEQ;
    public static final zzfz<String> zzER;
    public static final zzfz<String> zzES;
    public static final zzfz<Long> zzET;
    public static final zzfz<Boolean> zzEU;
    public static final zzfz<Boolean> zzEV;
    public static final zzfz<Boolean> zzEW;
    public static final zzfz<Long> zzEX;
    public static final zzfz<String> zzEY;
    public static final zzfz<Long> zzEZ;
    public static final zzfz<Boolean> zzEa;
    public static final zzfz<Boolean> zzEb;
    public static final zzfz<String> zzEc;
    public static final zzfz<String> zzEd;
    public static final zzfz<String> zzEe;
    public static final zzfz<Long> zzEf;
    public static final zzfz<Boolean> zzEg;
    public static final zzfz<Boolean> zzEh;
    public static final zzfz<String> zzEi;
    public static final zzfz<String> zzEj;
    public static final zzfz<String> zzEk;
    public static final zzfz<String> zzEl;
    public static final zzfz<Boolean> zzEm;
    public static final zzfz<Boolean> zzEn;
    public static final zzfz<String> zzEo;
    public static final zzfz<Boolean> zzEp;
    public static final zzfz<Boolean> zzEq;
    public static final zzfz<Boolean> zzEr;
    public static final zzfz<Integer> zzEs;
    public static final zzfz<String> zzEt;
    public static final zzfz<String> zzEu;
    public static final zzfz<Boolean> zzEv;
    public static final zzfz<Boolean> zzEw;
    public static final zzfz<Boolean> zzEx;
    public static final zzfz<Boolean> zzEy;
    public static final zzfz<Boolean> zzEz;
    public static final zzfz<Boolean> zzFa;
    public static final zzfz<Boolean> zzFb;
    public static final zzfz<Integer> zzFc;
    public static final zzfz<Long> zzFd;
    public static final zzfz<Boolean> zzFe;
    public static final zzfz<Boolean> zzFf;
    public static final zzfz<Boolean> zzFg;
    public static final zzfz<Long> zzFh;
    public static final zzfz<Boolean> zzFi;
    public static final zzfz<Boolean> zzFj;
    public static final zzfz<Boolean> zzFk;
    public static final zzfz<Boolean> zzFl;
    public static final zzfz<Boolean> zzFm;
    public static final zzfz<String> zzFn;
    public static final zzfz<String> zzFo;
    public static final zzfz<String> zzFp;
    public static final zzfz<String> zzFq;
    public static final zzfz<Integer> zzFr;
    public static final zzfz<Integer> zzFs;
    public static final zzfz<Boolean> zzFt;
    public static final zzfz<Boolean> zzFu;
    public static final zzfz<Integer> zzFv;
    private static byte[] zzFw;

    /* renamed from: com.google.android.gms.internal.zzgd.1 */
    class C11861 implements Callable<Void> {
        final /* synthetic */ Context zztf;

        C11861(Context context) {
            this.zztf = context;
        }

        public /* synthetic */ Object call() {
            return zzbk();
        }

        public Void zzbk() {
            zzw.zzcY().initialize(this.zztf);
            return null;
        }
    }

    static {
        zzBg = zzfz.zza(0, "gads:sdk_core_experiment_id");
        zzBh = zzfz.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        zzBi = zzfz.zza(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
        zzBj = zzfz.zza(0, "gads:request_builder:singleton_webview_experiment_id");
        zzBk = zzfz.zza(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
        zzBl = zzfz.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
        zzBm = zzfz.zza(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
        zzBn = zzfz.zza(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
        zzBo = zzfz.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
        zzBp = zzfz.zza(0, "gads:block_autoclicks", Boolean.valueOf(false));
        zzBq = zzfz.zza(0, "gads:block_autoclicks_experiment_id");
        zzBr = zzfz.zza(0, "gads:spam_app_context:experiment_id");
        zzBs = zzfz.zza(1, "gads:spam_app_context:enabled", Boolean.valueOf(false));
        zzBt = zzfz.zza(1, "gads:http_url_connection_factory:timeout_millis", (int) AbstractSpiCall.DEFAULT_TIMEOUT);
        zzBu = zzfz.zza(1, "gads:video_exo_player:version", "1");
        zzBv = zzfz.zza(0, "gads:video_stream_cache:experiment_id");
        zzBw = zzfz.zza(1, "gads:video_stream_cache:limit_count", 5);
        zzBx = zzfz.zza(1, "gads:video_stream_cache:limit_space", (int) AccessibilityEventCompat.TYPE_VIEW_CONTEXT_CLICKED);
        zzBy = zzfz.zza(1, "gads:video_stream_exo_allocator:segment_size", (int) AccessibilityNodeInfoCompat.ACTION_CUT);
        zzBz = zzfz.zza(1, "gads:video_stream_exo_cache:buffer_size", (int) AccessibilityEventCompat.TYPE_VIEW_CONTEXT_CLICKED);
        zzBA = zzfz.zza(1, "gads:video_stream_cache:limit_time_sec", 300);
        zzBB = zzfz.zza(1, "gads:video_stream_cache:notify_interval_millis", 1000);
        zzBC = zzfz.zza(1, "gads:video_stream_cache:connect_timeout_millis", (int) AbstractSpiCall.DEFAULT_TIMEOUT);
        zzBD = zzfz.zza(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
        zzBE = zzfz.zza(1, "gads:video:metric_frame_hash_times", FirebaseRemoteConfig.DEFAULT_VALUE_FOR_STRING);
        zzBF = zzfz.zza(1, "gads:video:metric_frame_hash_time_leniency", 500);
        zzBG = zzfz.zza(1, "gads:video:force_watermark", Boolean.valueOf(false));
        zzBH = zzfz.zza(1, "gads:video:surface_update_min_spacing_ms", 1000);
        zzBI = zzfz.zza(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
        zzBJ = zzfz.zza(1, "gads:video:spinner:scale", 4);
        zzBK = zzfz.zza(1, "gads:video:spinner:jank_threshold_ms", 50);
        zzBL = zzfz.zza(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
        zzBM = zzfz.zza(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
        zzBN = zzfz.zzb(0, "gads:spam_ad_id_decorator:experiment_id");
        zzBO = zzfz.zza(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
        zzBP = zzfz.zza(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
        zzBQ = zzfz.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
        zzBR = zzfz.zza(0, "gads:ad_id_app_context:experiment_id");
        zzBS = zzfz.zzb(0, "gads:looper_for_gms_client:experiment_id");
        zzBT = zzfz.zza(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
        zzBU = zzfz.zza(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
        zzBV = zzfz.zza(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
        zzBW = zzfz.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        zzBX = zzfz.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        zzBY = zzfz.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        zzBZ = zzfz.zza(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
        zzCa = zzfz.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        zzCb = zzfz.zza(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
        zzCc = zzfz.zza(0, "gads:enable_content_fetching", Boolean.valueOf(true));
        zzCd = zzfz.zza(0, "gads:content_length_weight", 1);
        zzCe = zzfz.zza(0, "gads:content_age_weight", 1);
        zzCf = zzfz.zza(0, "gads:min_content_len", 11);
        zzCg = zzfz.zza(0, "gads:fingerprint_number", 10);
        zzCh = zzfz.zza(0, "gads:sleep_sec", 10);
        zzCi = zzfz.zza(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
        zzCj = zzfz.zza(1, "gads:content_vertical_fingerprint_number", 100);
        zzCk = zzfz.zza(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
        zzCl = zzfz.zza(1, "gads:content_vertical_fingerprint_bits", 23);
        zzCm = zzfz.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
        zzCn = zzfz.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
        zzCo = zzfz.zza(1, "gads:content_fetch_exclude_view_tag", "none");
        zzCp = zzfz.zza(0, "gad:app_index_enabled", Boolean.valueOf(true));
        zzCq = zzfz.zza(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
        zzCr = zzfz.zza(0, "gads:app_index:timeout_ms", 1000);
        zzCs = zzfz.zza(0, "gads:app_index:experiment_id");
        zzCt = zzfz.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
        zzCu = zzfz.zza(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
        zzCv = zzfz.zza(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
        zzCw = zzfz.zza(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
        zzCx = zzfz.zza(0, "gads:interstitial_follow_url:experiment_id");
        zzCy = zzfz.zza(0, "gads:analytics_enabled", Boolean.valueOf(true));
        zzCz = zzfz.zza(0, "gads:ad_key_enabled", Boolean.valueOf(false));
        zzCA = zzfz.zza(1, "gads:sai:enabled", Boolean.valueOf(false));
        zzCB = zzfz.zza(1, "gads:sai:banner_ad_enabled", Boolean.valueOf(true));
        zzCC = zzfz.zza(1, "gads:sai:native_ad_enabled", Boolean.valueOf(true));
        zzCD = zzfz.zza(1, "gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
        zzCE = zzfz.zza(1, "gads:sai:click_ping_schema", "[\"/aclk\",\"/pcs/click\"]");
        zzCF = zzfz.zza(1, "gads:sai:impression_ping_schema", "[\"/adview\"]");
        zzCG = zzfz.zza(1, "gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
        zzCH = zzfz.zza(0, "gads:webview_cache_version", 0);
        zzCI = zzfz.zza(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
        zzCJ = zzfz.zza(1, "gads:webview_recycle:experiment_id");
        zzCK = zzfz.zza(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
        zzCL = zzfz.zzb(0, "gads:pan:experiment_id");
        zzCM = zzfz.zza(1, "gads:rewarded:experiment_id");
        zzCN = zzfz.zza(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
        zzCO = zzfz.zza(1, "gads:rewarded:adapter_timeout_ms", 20000);
        zzCP = zzfz.zza(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
        zzCQ = zzfz.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
        zzCR = zzfz.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
        zzCS = zzfz.zza(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
        zzCT = zzfz.zza(1, "gads:adid_values_in_adrequest:timeout", 2000);
        zzCU = zzfz.zza(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
        zzCV = zzfz.zza(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
        zzCW = zzfz.zza(1, "gads:ad_manager_enforce_arp_invariant:experiment_id");
        zzCX = zzfz.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
        zzCY = zzfz.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
        zzCZ = zzfz.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
        zzDa = zzfz.zza(1, "gads:banner_ad_pool:max_queues", 3);
        zzDb = zzfz.zza(1, "gads:banner_ad_pool:max_pools", 3);
        zzDc = zzfz.zza(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
        zzDd = zzfz.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
        zzDe = zzfz.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        zzDf = zzfz.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        zzDg = zzfz.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
        zzDh = zzfz.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        zzDi = zzfz.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        zzDj = zzfz.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        zzDk = zzfz.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
        zzDl = zzfz.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
        zzDm = zzfz.zza(1, "gads:interstitial_ad_pool:discard_threshold", Float.NaN);
        zzDn = zzfz.zza(1, "gads:heap_wastage:bytes", 0);
        zzDo = zzfz.zza(1, "gads:spherical_video:vertex_shader", FirebaseRemoteConfig.DEFAULT_VALUE_FOR_STRING);
        zzDp = zzfz.zza(1, "gads:spherical_video:fragment_shader", FirebaseRemoteConfig.DEFAULT_VALUE_FOR_STRING);
        zzDq = zzfz.zza(1, "gads:spherical_video:experiment_id");
        zzDr = zzfz.zza(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
        zzDs = zzfz.zza(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
        zzDt = zzfz.zza(1, "gads:include_local_global_rectangles:experiment_id");
        zzDu = zzfz.zza(1, "gads:position_watcher:throttle_ms", 200);
        zzDv = zzfz.zza(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
        zzDw = zzfz.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
        zzDx = zzfz.zza(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
        zzDy = zzfz.zza(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
        zzDz = zzfz.zza(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
        zzDA = zzfz.zza(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
        zzDB = zzfz.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
        zzDC = zzfz.zza(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
        zzDD = zzfz.zza(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
        zzDE = zzfz.zza(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
        zzDF = zzfz.zza(0, "gads:gmsg:video_meta:experiment_id");
        zzDG = zzfz.zza(1, "gads:network:cache_prediction_duration_s", 300);
        zzDH = zzfz.zza(1, "gads:network:network_prediction_timeout_ms", 2000);
        zzDI = zzfz.zza(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
        zzDJ = zzfz.zza(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
        zzDK = zzfz.zza(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
        zzDL = zzfz.zza(0, "gads:ad_loader:timeout_ms", 60000);
        zzDM = zzfz.zza(0, "gads:rendering:timeout_ms", 60000);
        zzDN = zzfz.zza(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
        zzDO = zzfz.zza(1, "gads:gestures:task_timeout", 2000);
        zzDP = zzfz.zza(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
        zzDQ = zzfz.zza(1, "gads:gestures:adb_query:enabled", Boolean.valueOf(false));
        zzDR = zzfz.zza(1, "gads:gestures:adb_click:enabled", Boolean.valueOf(false));
        zzDS = zzfz.zza(1, "gads:gestures:visibility:enabled", Boolean.valueOf(false));
        zzDT = zzfz.zza(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
        zzDU = zzfz.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
        zzDV = zzfz.zza(0, "gass:client:enabled", Boolean.valueOf(true));
        zzDW = zzfz.zza(0, "gass:enabled", Boolean.valueOf(true));
        zzDX = zzfz.zza(0, "gass:enable_int_signal", Boolean.valueOf(true));
        zzDY = zzfz.zza(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
        zzDZ = zzfz.zza(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
        zzEa = zzfz.zza(0, "gads:support_screen_shot", Boolean.valueOf(true));
        zzEb = zzfz.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
        zzEc = zzfz.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
        zzEd = zzfz.zza(1, "gads:sdk_core_constants:experiment_id");
        zzEe = zzfz.zza(1, "gads:sdk_core_constants:caps", FirebaseRemoteConfig.DEFAULT_VALUE_FOR_STRING);
        zzEf = zzfz.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        zzEg = zzfz.zza(0, "gads:js_flags:mf", Boolean.valueOf(false));
        zzEh = zzfz.zza(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
        zzEi = zzfz.zza(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        zzEj = zzfz.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        zzEk = zzfz.zza(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
        zzEl = zzfz.zza(1, "gads:native:video_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
        zzEm = zzfz.zza(1, "gads:singleton_webview_native", Boolean.valueOf(false));
        zzEn = zzfz.zza(1, "gads:native_initialize_Webview_request_time", Boolean.valueOf(false));
        zzEo = zzfz.zza(1, "gads:singleton_webview_native:experiment_id");
        zzEp = zzfz.zza(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
        zzEq = zzfz.zza(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
        zzEr = zzfz.zza(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
        zzEs = zzfz.zza(1, "gads:native_video_load_timeout", 10);
        zzEt = zzfz.zza(1, "gads:native_video_load_timeout:experiment_id");
        zzEu = zzfz.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
        zzEv = zzfz.zza(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
        zzEw = zzfz.zza(1, "gads:enable_tracking_for_native_ad_views", Boolean.valueOf(true));
        zzEx = zzfz.zza(1, "gads:use_new_json_for_native_view_tracking", Boolean.valueOf(true));
        zzEy = zzfz.zza(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
        zzEz = zzfz.zza(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
        zzEA = zzfz.zza(0, "gads:method_tracing:duration_ms", 30000);
        zzEB = zzfz.zza(0, "gads:method_tracing:count", 5);
        zzEC = zzfz.zza(0, "gads:method_tracing:filesize", 134217728);
        zzED = zzfz.zza(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
        zzEE = zzfz.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
        zzEF = zzfz.zza(1, "gads:auto_location_timeout", 2000);
        zzEG = zzfz.zzb(1, "gads:auto_location_timeout:experiment_id");
        zzEH = zzfz.zza(1, "gads:auto_location_interval", -1);
        zzEI = zzfz.zzb(1, "gads:auto_location_interval:experiment_id");
        zzEJ = zzfz.zza(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
        zzEK = zzfz.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
        zzEL = zzfz.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
        zzEM = zzfz.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
        zzEN = zzfz.zza(0, "gads:afs:csa:experiment_id");
        zzEO = zzfz.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
        zzEP = zzfz.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
        zzEQ = zzfz.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
        zzER = zzfz.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
        zzES = zzfz.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
        zzET = zzfz.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
        zzEU = zzfz.zza(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
        zzEV = zzfz.zza(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
        zzEW = zzfz.zza(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
        zzEX = zzfz.zza(1, "gads:parental_controls:timeout", 2000);
        zzEY = zzfz.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        zzEZ = zzfz.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
        zzFa = zzfz.zza(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
        zzFb = zzfz.zza(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
        zzFc = zzfz.zza(1, "gads:cache:max_concurrent_downloads", 10);
        zzFd = zzfz.zza(1, "gads:cache:javascript_timeout_millis", 5000);
        zzFe = zzfz.zza(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
        zzFf = zzfz.zza(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
        zzFg = zzfz.zza(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
        zzFh = zzfz.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
        zzFi = zzfz.zza(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
        zzFj = zzfz.zza(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
        zzFk = zzfz.zza(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
        zzFl = zzfz.zza(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(false));
        zzFm = zzfz.zza(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(false));
        zzFn = zzfz.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        zzFo = zzfz.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        zzFp = zzfz.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        zzFq = zzfz.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        zzFr = zzfz.zza(1, "gads:drx_debug:timeout_ms", 5000);
        zzFs = zzfz.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
        zzFt = zzfz.zza(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
        zzFu = zzfz.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
        zzFv = zzfz.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    }

    public static void initialize(Context context) {
        zzqb.zzb(new C11861(context));
        int intValue = ((Integer) zzDn.get()).intValue();
        if (intValue > 0 && zzFw == null) {
            zzFw = new byte[intValue];
        }
    }

    public static List<String> zzfs() {
        return zzw.zzcX().zzfs();
    }

    public static List<String> zzft() {
        return zzw.zzcX().zzft();
    }
}
